server:
  port: 9090
  servlet:
    context-path: /admin
    
spring:
  data:
    mongodb:
      uri: mongodb://spring:password1234@books-mongodb:27017/booksonline
    
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://gutenberg-eureka:8761/eureka/
