server:
  port: 8084
  servlet:
    context-path:
    
spring:
  data:
    mongodb:
      uri: mongodb://spring:password1234@mongodb-books:27017/booksonline
    
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKASERVER_URI}


#baseUsersUrl: http://localhost:8084 
baseUsersUrl: ${BASE_USERS_URL}
