server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native: 
          searchLocations: file:/tmp/config-repo
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKASERVER_URI}
 
